import "IconMode.idl";
import "NavigationMode.idl";
import "NavigationRequestedEventArgs.idl";
namespace SwipeNavigation
{
runtimeclass SwipeNavigator : Windows.UI.Xaml.Controls.ContentControl
{
SwipeNavigator();
static Windows.UI.Xaml.Visibility BackDropIconVisibility(SwipeNavigation.IconMode mode);
static Windows.UI.Xaml.DependencyProperty BackNavigationModeProperty{get;};
SwipeNavigation.NavigationMode BackNavigationMode;
static Windows.UI.Xaml.DependencyProperty CanGoBackProperty{get;};
Boolean CanGoBack;
static Windows.UI.Xaml.DependencyProperty CanGoForwardProperty{get;};
Boolean CanGoForward;
void Close();
void Close(Boolean withAnimation);
static SwipeNavigation.SwipeNavigator Find(Windows.UI.Xaml.FrameworkElement element);
static Windows.UI.Xaml.DependencyProperty ForwardNavigationModeProperty{get;};
SwipeNavigation.NavigationMode ForwardNavigationMode;
Windows.UI.Xaml.Controls.Frame Frame;
static Windows.UI.Xaml.DependencyProperty IconModeProperty{get;};
SwipeNavigation.IconMode IconMode;
void OnApplyTemplate();
static Windows.UI.Xaml.Visibility OverlayIconVisibility(SwipeNavigation.IconMode mode);
static Windows.UI.Xaml.DependencyProperty RevealWidthProperty{get;};
Double RevealWidth;
event Windows.Foundation.TypedEventHandler<SwipeNavigation.SwipeNavigator, SwipeNavigation.NavigationRequestedEventArgs> BackRequested;
event Windows.Foundation.TypedEventHandler<SwipeNavigation.SwipeNavigator, SwipeNavigation.NavigationRequestedEventArgs> ForwardRequested;
}
}
