name: CI

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - run: ./SwipeNavigator/scripts/test
  build:
    runs-on: windows-2022
    needs: ["test"]
    if: startsWith(github.ref, 'refs/tags')
    env:
      VERSION: 0.1.2
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - working-directory: SwipeNavigator
        run: |
          ./scripts/build -version $env:VERSION
          ./scripts/publish-nuget -version $env:VERSION
